site_name: lite-bootstrap
site_url: https://lite-bootstrap.modern-python.org
repo_url: https://github.com/modern-python/lite-bootstrap
docs_dir: docs
edit_uri: edit/main/docs/
nav:
  - Introduction:
      - Quickstart: introduction/quickstart.md
      - Installation: introduction/installation.md
      - Configuration: introduction/configuration.md
  - Integrations:
      - Litestar: integrations/litestar.md
      - FastStream: integrations/faststream.md
      - FastAPI: integrations/fastapi.md
      - FastMCP: integrations/fastmcp.md
      - Free bootstrapper: integrations/free.md
theme:
  name: material
  logo: assets/mark.svg
  favicon: assets/favicon.svg
  features:
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - navigation.footer
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.instant
    - header.autohide
    - announce.dismiss
  icon:
    edit: material/pencil
    view: material/eye
    repo: fontawesome/brands/git-alt
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - codehilite:
      use_pygments: true
  - attr_list
  - md_in_html

extra_css:
  - css/code.css
  - css/brand.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/modern-python/lite-bootstrap
      name: GitHub
